# Generated by Django 3.1.7 on 2021-03-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolNegEmpresaCae',
            fields=[
                ('dim_3', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dim3_t', models.CharField(blank=True, max_length=255, null=True)),
                ('total_ultimo_pref', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vol_neg_empresa_cae',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolNegEmpresaRegiao',
            fields=[
                ('geocod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('geodsg', models.CharField(blank=True, max_length=150, null=True)),
                ('total_ultimo_pref', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vol_neg_empresa_regiao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolNegEmpresaDados',
            fields=[
                ('geocod', models.OneToOneField(db_column='geocod', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.volnegempresaregiao')),
                ('valor', models.BigIntegerField(blank=True, null=True)),
                ('ultimo_pref', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'vol_neg_empresa_dados',
                'managed': False,
            },
        ),
    ]
