# Generated by Django 3.1.7 on 2021-05-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_volnegempresacae_volnegempresadados_volnegempresaregiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('requisitos_entrada', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'instituicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('qualificacao', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('campo_estudo', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('valor_anual_nacional', models.CharField(max_length=255)),
                ('valor_anual_internacional', models.CharField(max_length=255)),
                ('duracao', models.CharField(max_length=255)),
                ('modo', models.CharField(max_length=255)),
                ('data_raspagem', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('requisitos', models.CharField(max_length=255)),
                ('remuneracao', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('modo', models.CharField(max_length=255)),
                ('data_raspagem', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil_trabalho',
                'managed': False,
            },
        ),
    ]
