# Generated by Django 3.1.7 on 2021-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_instituicao_perfilcurso_perfiltrabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('last_extraction', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('populated', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provenance_statement',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SourceData',
        ),
    ]
