# Generated by Django 3.1.7 on 2021-07-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210716_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeOrUniversity',
            fields=[
                ('PartitionKey', models.CharField(blank=True, max_length=255, null=True)),
                ('RowKey', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(blank=True, null=True)),
                ('entityid', models.CharField(blank=True, max_length=255, null=True)),
                ('codigodoestabelecimento', models.CharField(blank=True, max_length=255, null=True)),
                ('nomedoestabelecimento', models.CharField(blank=True, max_length=255, null=True)),
                ('morada', models.CharField(blank=True, max_length=255, null=True)),
                ('codigopostal', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('concelho', models.CharField(blank=True, max_length=255, null=True)),
                ('tipodeensino', models.CharField(blank=True, max_length=255, null=True)),
                ('paginaweb', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('codigodependede', models.CharField(blank=True, max_length=255, null=True)),
                ('dependede', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'college_or_university',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('PartitionKey', models.CharField(blank=True, max_length=255, null=True)),
                ('RowKey', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(blank=True, null=True)),
                ('entityid', models.CharField(blank=True, max_length=255, null=True)),
                ('subsistema', models.CharField(blank=True, max_length=255, null=True)),
                ('tipodeensino', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('estabelecimento', models.CharField(blank=True, max_length=255, null=True)),
                ('curso', models.CharField(blank=True, max_length=255, null=True)),
                ('niveldeformacao', models.CharField(blank=True, max_length=255, null=True)),
                ('areacnaef', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ClassNacionaldeareasdeeducacaoeformacao',
        ),
        migrations.DeleteModel(
            name='InstituicoesdoEnsinoSuperior',
        ),
    ]
