# Generated by Django 3.1.7 on 2021-07-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210717_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCnaef',
            fields=[
                ('PartitionKey', models.CharField(blank=True, max_length=255, null=True)),
                ('RowKey', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(blank=True, null=True)),
                ('entityid', models.CharField(blank=True, max_length=255, null=True)),
                ('subsistema', models.CharField(blank=True, max_length=255, null=True)),
                ('tipodeensino', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('estabelecimento', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('niveldeformacao', models.CharField(blank=True, max_length=255, null=True)),
                ('areacnaef', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'curso_cnaef',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.CharField(blank=True, max_length=2048, null=True)),
                ('requisitos', models.CharField(max_length=255)),
                ('remuneracao', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('modo', models.CharField(max_length=255)),
                ('area_curso', models.CharField(max_length=255)),
                ('data_raspagem', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil_trabalho',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
        migrations.DeleteModel(
            name='PerfilCurso',
        ),
        migrations.DeleteModel(
            name='PerfilTrabalho',
        ),
        migrations.DeleteModel(
            name='VolNegEmpresaCae',
        ),
        migrations.DeleteModel(
            name='VolNegEmpresaDados',
        ),
        migrations.DeleteModel(
            name='VolNegEmpresaRegiao',
        ),
    ]
