# Generated by Django 3.1.7 on 2021-08-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210717_1242'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trabalho',
            table='trabalho',
        ),
    ]
