# Generated by Django 3.1.7 on 2021-08-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210812_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeOrUniversity',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='CursoCnaef',
        ),
        migrations.DeleteModel(
            name='ProvenanceStatement',
        ),
        migrations.DeleteModel(
            name='Trabalho',
        ),
    ]
