# Generated by Django 3.1.7 on 2021-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_auto_20210813_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeOrUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowkey', models.CharField(blank=True, db_column='RowKey', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('entityid', models.CharField(blank=True, max_length=255, null=True)),
                ('codigodoestabelecimento', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nomedoestabelecimento', models.CharField(blank=True, max_length=255, null=True)),
                ('morada', models.CharField(blank=True, max_length=255, null=True)),
                ('codigopostal', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('concelho', models.CharField(blank=True, max_length=255, null=True)),
                ('tipodeensino', models.CharField(blank=True, max_length=255, null=True)),
                ('paginaweb', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('partitionkey', models.CharField(blank=True, db_column='PartitionKey', max_length=255, null=True)),
                ('codigodependede', models.CharField(blank=True, max_length=255, null=True)),
                ('dependede', models.CharField(blank=True, max_length=255, null=True)),
                ('link_open_data', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'college_or_university',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=4096, null=True)),
                ('valor_propina_nacional', models.IntegerField(blank=True, null=True)),
                ('valor_propina_internacional', models.IntegerField(blank=True, null=True)),
                ('duracao', models.CharField(blank=True, max_length=50, null=True)),
                ('modo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoCnaef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowkey', models.CharField(blank=True, db_column='RowKey', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('entityid', models.CharField(blank=True, max_length=255, null=True)),
                ('subsistema', models.CharField(blank=True, max_length=255, null=True)),
                ('tipodeensino', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('niveldeformacao', models.CharField(blank=True, max_length=255, null=True)),
                ('areacnaef', models.CharField(blank=True, max_length=255, null=True)),
                ('partitionkey', models.CharField(blank=True, db_column='PartitionKey', max_length=255, null=True)),
            ],
            options={
                'db_table': 'curso_cnaef',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvenanceStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('last_extraction', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('populated', models.BooleanField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provenance_statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=4096, null=True)),
                ('requisitos', models.CharField(blank=True, max_length=255, null=True)),
                ('remuneracao', models.CharField(blank=True, max_length=20, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('modo', models.CharField(blank=True, max_length=255, null=True)),
                ('area_curso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'trabalho',
                'managed': False,
            },
        ),
    ]
